# docker-compose.yml
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./downloads:/app/downloads
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - LOG_ENV=development
      - PYTHONUNBUFFERED=1

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./downloads/pending:/app/downloads/pending

      - '/mnt/c/botDownloads/bot-xml-gms:/app/downloads/processed'

      - ./logs:/app/logs
    depends_on:
      - redis
    environment:
      - LOG_ENV=development
      - PYTHONUNBUFFERED=1
