# docker-compose.prod.yml
# Configuração para o ambiente de produção no servidor

version: '3.8'

services:
  redis:
    image: "redis:alpine"

  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - bot-logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - LOG_ENV=production
      - PYTHONUNBUFFERED=1

  worker:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - '/mnt/c/Automations/bot-xml-gms/pending-downloads:/app/downloads/pending'
      - '/mnt/c/Automations/bot-xml-gms/processed-downloads:/app/downloads/processed'
      - '/mnt/c/Automations/bot-xml-gms/logs:/app/logs'
    depends_on:
      - redis
    environment:
      - LOG_ENV=production
      - PYTHONUNBUFFERED=1
      - GMS_USER=${GMS_USER}
      - GMS_PASSWORD=${GMS_PASSWORD}

volumes:
  bot-logs:
  bot-pending-downloads:
  bot-processed-downloads:
