services:

  gms-xml-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gms-xml-worker
    environment:
      - RABBITMQ_HOST=maestro_rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_QUEUE=automation_jobs

      - MAESTRO_DB_HOST=maestro_postgres
      - MAESTRO_DB_PORT=5432
      - MAESTRO_DB_USER=user
      - MAESTRO_DB_PASSWORD=password
      - MAESTRO_DB_NAME=maestro_db

      - GMS_USER=${GMS_USER}
      - GMS_PASSWORD=${GMS_PASSWORD}
      - WORKER_ID=gms-worker-01
      - LOG_LEVEL=INFO

    networks:
      - maestro-network
    restart: unless-stopped
