# config/selectors.yaml
login_page:
  username_input: "[data-cy='login-usuario-input-field']"
  password_input: "[data-cy='login-senha-input-field']"
  login_button: "[data-cy='login-entrar-button']"

home_page:
  sidebar_tax: "#sidemenu-item-3"
  sidebar_tax_integration: "#sidemenu-item-51"
  sidebar_tax_integration_export: "#sidemenu-item-1800"

export_page:
  legado_frame: "//iframe[@id='legadoFrame']"
  include_button: "#botaoIncluir"
  popup_frame: "//iframe[@id='frameExportacaoDocumento']"