# config/selectors.yaml
login_page:
  username_input: "#input-19" # seletor CSS
  password_input: "#input-20" # seletor CSS
  login_button: ".flora-button.flora-button--text-only.flora-button--standard.flora-button--shape-small.flora-button--size-standard.flora-body-small[disabled='disabled']"

home_page:
  # Exemplo: XPath para um link que contém o texto 'Exportação'
  export_link: "//a[contains(text(), 'Exportação')]"

export_page:
  start_date_input: "#data-inicial" # Exemplo: ID do campo de data inicial
  end_date_input: "#data-final"
  store_select_dropdown: "#filial-select"
  generate_report_button: "button.btn-primary"
  # Seletor para um ícone ou mensagem que indica que o download começou/terminou
  download_status_indicator: ".download-complete-toast"