# config/selectors.yaml
login_page:
  username_input: "[data-cy='login-usuario-input-field']"
  password_input: "[data-cy='login-senha-input-field']"
  login_button: "[data-cy='login-entrar-button']"

home_page:
  sidebar_tax: "#sidemenu-item-3"
  sidebar_tax_integration: "#sidemenu-item-51"
  sidebar_tax_integration_export: "#sidemenu-item-1800"

export_page:
  legado_frame: "//iframe[@id='legadoFrame']"
  popup_frame: "//iframe[@id='frameExportacaoDocumento']"
  popup_header: ".modal-header"
  include_button: "#botaoIncluir"
  document_type_dropdown: "#documentos"
  emitter_dropdown: "#emissor"
  operation_type_dropdown: "#tipoDeOperacao" 
  operation_type_span: "#select2-tipoDeOperacao-container"
  file_type_dropdown: "#tipoArquivo"
  invoice_situation_dropdown: "#situacaoNota"
  stores_input: "input[role='listbox']"
  stores_selector: "input[role='listbox']"
  start_date_input: "#dataInicio"
  end_date_input: "#dataFim"
  export_button: "#btn_salvar"
  alert_msg: ".alerta-msg"
  search_button: "#botaoPesquisar"
  table_rows: "//tr[@role='row']"
  download_button: "#baixarDocumentos"