# .github/workflows/deploy.yml
name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    
    runs-on: self-hosted
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Navigate to Project Directory
      run: cd ~/bot-xml-gms

    - name: Pull Latest Changes
      run: git pull origin main

    - name: Build and Start Docker Compose Production
      run: docker-compose -f docker-compose.prod.yml up --build -d
      
    - name: Clean up old docker images
      if: always()
      run: docker image prune -a -f